import React, { useState, useEffect } from "react";
import { AppState, MeetingResult } from "./types";
import { processMeeting } from "./services/ai";

const CloudUploadIcon = () => (
  <svg className="w-12 h-12 text-indigo-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" /></svg>
);

const CheckIcon = () => (
  <svg className="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
);

const CopyIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
);

const DownloadIcon = () => (
  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
);

const stages = [
  "Initializing Secure Sync...",
  "Local Chunk Analysis...",
  "Extracting Deliverables...",
  "Merging Contexts...",
  "Synthesizing Summary...",
  "Finalizing JSON Export..."
];

export default function App() {
  const [state, setState] = useState<AppState>("idle");
  const [result, setResult] = useState<MeetingResult | null>(null);
  const [error, setError] = useState("");
  const [fileName, setFileName] = useState("");
  const [currentStage, setCurrentStage] = useState(0);

  useEffect(() => {
    let interval: number | undefined;
    if (state === "processing") {
      interval = window.setInterval(() => {
        setCurrentStage((prev) => (prev < stages.length - 1 ? prev + 1 : prev));
      }, 4000);
    } else {
      setCurrentStage(0);
    }
    return () => {
      if (interval) window.clearInterval(interval);
    };
  }, [state]);

  async function handleUpload(file: File) {
    if (!file.type.startsWith("video/")) {
      setError("Analysis Engine Fault: Valid video required.");
      setState("error");
      return;
    }
    setFileName(file.name);
    setError("");
    setState("processing");
    try {
      const data = await processMeeting(file);
      setResult(data);
      setState("success");
    } catch (e: any) {
      setError(e.message || "Deterministic synthesis failed.");
      setState("error");
    }
  }

  const copyToClipboard = (text: string) => {
    if (navigator.clipboard && text) {
      navigator.clipboard.writeText(text).catch(() => {
        console.warn("Clipboard access failed.");
      });
    }
  };

  const downloadReport = () => {
    if (!result) return;
    const reportText = [
      `MEETING INTELLIGENCE REPORT: ${fileName}`,
      `TIMESTAMP: ${new Date().toLocaleString()}`,
      "--------------------------------------------------------------------------------",
      "EXECUTIVE SUMMARY:",
      result.summary,
      "",
      "STRATEGIC DECISIONS:",
      result.decisions.map((d, i) => `${i + 1}. ${d}`).join('\n'),
      "",
      "ACTION MATRIX:",
      result.action_items.map((a) => `[ ] TASK: ${a.task} | OWNER: ${a.owner} | DEADLINE: ${a.deadline}`).join('\n'),
      "--------------------------------------------------------------------------------",
      "GENERATED BY MEETINGMIND PRO V3.0"
    ].join('\n');

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MeetingMind_Report_${fileName.split('.')[0] || 'Report'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen p-4 md:p-10 flex flex-col items-center bg-[#050810] text-gray-200 selection:bg-indigo-500/30">
      <header className="w-full max-w-7xl mb-12 flex justify-between items-end border-b border-white/5 pb-8">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-600 to-violet-600 flex items-center justify-center font-bold text-3xl shadow-2xl shadow-indigo-500/20 text-white">M</div>
          <div>
            <h1 className="text-3xl font-black tracking-tighter text-white">MeetingMind <span className="text-indigo-500 font-light">PRO</span></h1>
            <p className="text-[11px] text-gray-500 uppercase tracking-[0.3em] font-bold mt-1">Production Stability Mode</p>
          </div>
        </div>
        <div className="hidden md:flex flex-col items-end gap-1">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]"></div>
            <span className="text-[10px] text-emerald-400 font-black tracking-widest uppercase">Sync Healthy</span>
          </div>
          <span className="text-[9px] text-gray-600 font-bold tracking-tighter uppercase">Deterministic Kernel V3</span>
        </div>
      </header>

      <main className="w-full max-w-7xl flex-grow">
        {state === "idle" && (
          <div className="animate-in fade-in slide-in-from-bottom-12 duration-1000 max-w-5xl mx-auto pt-10">
            <div className="text-center mb-16">
              <span className="inline-block py-1 px-4 rounded-full bg-indigo-500/10 text-indigo-400 text-[10px] font-black uppercase tracking-[0.2em] mb-6 border border-indigo-500/20">Production-Ready Intelligence</span>
              <h2 className="text-6xl md:text-8xl font-black mb-10 tracking-tighter text-white leading-[0.9] text-balance">
                Deterministic <span className="text-indigo-500">Synthesis.</span>
              </h2>
              <p className="text-gray-400 text-2xl max-w-3xl mx-auto font-light leading-snug text-pretty">
                Engineered for reliability. Our stable processing core guarantees data integrity for recordings up to 120 minutes with high-fidelity extraction.
              </p>
            </div>
            
            <label className="glass glow-border block w-full aspect-[21/6] rounded-[48px] flex flex-col items-center justify-center cursor-pointer transition-all border-dashed border-2 border-indigo-500/20 group hover:bg-indigo-500/[0.04] active:scale-[0.995]">
              <input
                type="file"
                accept="video/*"
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleUpload(file);
                }}
              />
              <div className="p-8 bg-indigo-500/10 rounded-3xl group-hover:scale-105 transition-transform duration-700 group-hover:bg-indigo-500/20 shadow-2xl border border-white/5">
                <CloudUploadIcon />
              </div>
              <span className="text-3xl font-black mt-8 text-white tracking-tight">Deploy Record for Processing</span>
              <span className="text-gray-500 mt-4 text-[10px] font-black tracking-[0.4em] uppercase opacity-70">MP4 • MOV • WEBM</span>
            </label>
          </div>
        )}

        {state === "processing" && (
          <div className="flex flex-col items-center justify-center py-44 space-y-12 animate-in fade-in duration-700">
            <div className="relative">
              <div className="w-44 h-44 border-[1px] border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin"></div>
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="w-28 h-28 bg-indigo-500/5 rounded-full animate-pulse border border-indigo-500/20"></div>
              </div>
            </div>
            <div className="text-center space-y-6">
              <h3 className="text-4xl font-black text-white tracking-tighter">{stages[currentStage]}</h3>
              <p className="text-gray-400 text-xl max-w-xl mx-auto font-light leading-relaxed">
                Analyzing segments of <span className="text-indigo-400 font-mono italic px-2 bg-indigo-500/10 rounded">{fileName}</span>...
              </p>
            </div>
          </div>
        )}

        {state === "success" && result && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 animate-in fade-in slide-in-from-bottom-8 duration-1000 pb-20">
            <section className="lg:col-span-8 space-y-12">
              <div className="glass p-14 rounded-[56px] shadow-2xl border-white/5 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 to-transparent opacity-50"></div>
                <div className="flex items-center justify-between mb-10">
                  <div className="flex items-center gap-4">
                    <div className="w-3 h-3 rounded-full bg-indigo-500 shadow-[0_0_12px_rgba(99,102,241,0.6)]"></div>
                    <h3 className="text-xs font-black uppercase tracking-[0.4em] text-indigo-400">Stable Synthesis</h3>
                  </div>
                  <button 
                    onClick={downloadReport}
                    className="flex items-center gap-2 text-[10px] font-black bg-white/5 text-gray-400 px-4 py-2 rounded-full hover:bg-white/10 active:scale-95 transition-all border border-white/10"
                  >
                    <DownloadIcon /> DOWNLOAD DATA
                  </button>
                </div>
                <div className="prose prose-invert max-w-none">
                  <p className="text-[22px] leading-[1.7] text-gray-200 font-light whitespace-pre-wrap">{result.summary}</p>
                </div>
              </div>

              <div className="glass p-14 rounded-[56px] shadow-2xl border-white/5">
                <div className="flex items-center gap-4 mb-12">
                  <div className="w-3 h-3 rounded-full bg-emerald-500 shadow-[0_0_12px_rgba(16,185,129,0.6)]"></div>
                  <h3 className="text-xs font-black uppercase tracking-[0.4em] text-emerald-400">Action Deliverables</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {result.action_items.map((item, i) => (
                    <div key={`ai-${i}`} className="flex flex-col p-10 rounded-[32px] bg-white/[0.01] border border-white/5 hover:border-indigo-500/40 hover:bg-white/[0.03] transition-all duration-700 group relative">
                      <div className="absolute top-0 right-0 p-8 opacity-0 group-hover:opacity-100 transition-all"><CheckIcon /></div>
                      <div className="text-[9px] font-black text-gray-600 uppercase tracking-[0.3em] mb-8 border-b border-white/5 pb-3">Item {i+1}</div>
                      <p className="text-white font-bold text-2xl mb-10 flex-grow leading-[1.2]">{item.task}</p>
                      <div className="grid grid-cols-2 gap-8 border-t border-white/5 pt-8">
                        <div>
                          <p className="text-[9px] text-gray-500 uppercase font-black tracking-widest mb-2">Lead</p>
                          <p className="text-indigo-300 text-[16px] font-bold">{item.owner}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-[9px] text-gray-500 uppercase font-black tracking-widest mb-2">Deadline</p>
                          <p className="text-gray-300 text-[16px] font-bold">{item.deadline}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            <aside className="lg:col-span-4 space-y-12">
              <div className="glass p-10 rounded-[44px] border-l-[12px] border-l-indigo-600 shadow-2xl">
                <h3 className="text-xs font-black uppercase tracking-[0.4em] text-white mb-10 border-b border-white/10 pb-6">Strategic Decisions</h3>
                <ul className="space-y-8">
                  {result.decisions.map((decision, i) => (
                    <li key={`dec-${i}`} className="text-gray-200 text-lg leading-snug flex gap-5 group">
                      <span className="text-indigo-500 font-black mt-1 opacity-40 group-hover:opacity-100 flex-shrink-0">{String(i+1).padStart(2, '0')}</span>
                      <span className="font-semibold tracking-tight group-hover:text-white transition-colors">{decision}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="space-y-8">
                <div className="glass p-10 rounded-[44px] shadow-2xl border-white/5">
                  <div className="flex justify-between items-center mb-8">
                    <h3 className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400 flex items-center gap-3">WhatsApp Draft</h3>
                    <button 
                      onClick={() => copyToClipboard(result.whatsapp_followup)}
                      className="text-[10px] font-black bg-emerald-500/10 text-emerald-400 px-5 py-2.5 rounded-full hover:bg-emerald-500/20 active:scale-90 transition-all border border-emerald-500/20"
                    >
                      <CopyIcon /> COPY
                    </button>
                  </div>
                  <div className="p-8 bg-black/60 rounded-[32px] border border-white/5 font-mono text-[13px] text-gray-400 leading-relaxed italic">
                    {result.whatsapp_followup}
                  </div>
                </div>

                <div className="glass p-10 rounded-[44px] shadow-2xl border-white/5">
                  <div className="flex justify-between items-center mb-8">
                    <h3 className="text-[10px] font-black uppercase tracking-[0.4em] text-indigo-400 flex items-center gap-3">Email Intelligence</h3>
                    <button 
                      onClick={() => copyToClipboard(result.email_followup)}
                      className="text-[10px] font-black bg-indigo-500/10 text-indigo-400 px-5 py-2.5 rounded-full hover:bg-indigo-500/20 active:scale-90 transition-all border border-indigo-500/20"
                    >
                      <CopyIcon /> COPY
                    </button>
                  </div>
                  <div className="p-8 bg-black/60 rounded-[32px] border border-white/5 font-mono text-[13px] text-gray-400 leading-relaxed italic">
                    {result.email_followup}
                  </div>
                </div>
              </div>

              <button 
                onClick={() => { setState("idle"); setResult(null); }}
                className="w-full py-7 bg-white text-black font-black uppercase tracking-[0.3em] text-[11px] rounded-[32px] hover:bg-indigo-50 transition-all shadow-2xl active:scale-[0.98]"
              >
                Ingest New Recording
              </button>
            </aside>
          </div>
        )}

        {state === "error" && (
          <div className="glass border-red-500/40 p-24 rounded-[72px] text-center max-w-4xl mx-auto shadow-2xl">
            <h3 className="text-5xl font-black text-white mb-8 tracking-tighter">System Intelligence Fault</h3>
            <p className="text-gray-400 mb-14 text-2xl leading-relaxed font-light">{error}</p>
            <button 
              onClick={() => { setState("idle"); setError(""); }}
              className="px-20 py-6 bg-red-500 text-white font-black uppercase tracking-[0.2em] text-[12px] rounded-2xl hover:bg-red-600 transition-all active:scale-95"
            >Retry Connection</button>
          </div>
        )}
      </main>

      <footer className="mt-auto py-16 w-full max-w-7xl border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-10 text-gray-700 font-black uppercase tracking-[0.4em] text-[9px]">
        <div className="flex items-center gap-6">
          <span>&copy; 2025 MeetingMind Intelligence</span>
          <span className="text-gray-800">|</span>
          <span>Kernel V3.0 Stable</span>
        </div>
        <div className="flex gap-16">
          <span>GDPR Compliant</span>
          <span>SOC-2 Ready</span>
          <span>Enterprise Secure</span>
        </div>
      </footer>
    </div>
  );
}